// <auto-generated />
using System;
using DominoWebApi.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DominoWebApi.Migrations
{
    [DbContext(typeof(DominoDbContext))]
    partial class DominoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DominoWebApi.Models.Question", b =>
                {
                    b.Property<string>("QuestionText")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Category")
                        .IsRequired();

                    b.Property<string>("CorrectAnswer")
                        .IsRequired();

                    b.Property<string>("WrongAnswer1")
                        .IsRequired();

                    b.Property<string>("WrongAnswer2")
                        .IsRequired();

                    b.Property<string>("WrongAnswer3")
                        .IsRequired();

                    b.HasKey("QuestionText");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("DominoWebApi.Models.Score", b =>
                {
                    b.Property<Guid>("ScoreId")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("PlayerId");

                    b.Property<int>("Points");

                    b.HasKey("ScoreId");

                    b.ToTable("Highscore");
                });
#pragma warning restore 612, 618
        }
    }
}
